"""create profiles table

Revision ID: eab8b2b1f42d
Revises: 12947bc96cf8
Create Date: 2026-09-05 12:03:28.576729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'eab8b2b1f42d'
down_revision: Union[str, None] = '12947bc96cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('university', sa.String(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('graduation_year', sa.Integer(), nullable=False),
    sa.Column('skills', postgresql.ARRAY(sa.Text()), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('bio', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('char_length(bio) <= 280', name='ck_profiles_bio_length'),
    sa.CheckConstraint('graduation_year BETWEEN 2015 AND 2035', name='ck_profiles_graduation_year_range'),
    sa.ForeignKeyConstraint(['id'], ['auth.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_profiles_skills', 'profiles', ['skills'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_profiles_skills', table_name='profiles', postgresql_using='gin')
    op.drop_table('profiles')
    # ### end Alembic commands ###
